server:
  port: 5000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:3310/cet4?userSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT"
    username: root
    password: '000000'
  #模板引擎
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    enabled: true
    cache: false
    check-template: true
    check-template-location: true
    servlet:
      content-type: text/html
  #邮件
  mail:
    username: ylzlcl@163.com
    password: {{you password}}
    host: smtp.163.com
    default-encoding: UTF-8
# trace < debug < info < warn < error < fatal
logging:
  level:
    root: info
#mybatis:
#  mapper-locations: com.cet4.mapper
#  type-aliases-package: com.cet4.dao
# 打印sql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


